"""Explicit public runtime API for Codex Project Harness."""

from __future__ import annotations

from harness_db import (
    DB_PATH,
    HarnessError,
    accept_task,
    add_acceptance,
    add_failure_mode,
    add_requirement,
    add_task,
    add_test_target,
    baseline_diff,
    baseline_validate,
    block_task,
    cancel_task,
    connection,
    cycle_close,
    cycle_start,
    cycle_status,
    doctor,
    freeze_baseline,
    get_store,
    init_runtime,
    link_requirement_acceptance,
    link_task_test_target,
    list_tasks,
    list_test_targets,
    migrate,
    quickstart_minimal,
    quickstart_status,
    quickstart_status_lines,
    record_decision,
    record_delivery,
    record_finding,
    record_gate,
    record_validation,
    repair,
    runtime_initialized,
    set_store_factory,
    start_task,
    status_lines,
    submit_task,
    trace_show,
    trace_validate,
    transaction,
    uninitialized_lines,
    validate_runtime,
    verify_run,
)


__all__ = (
    "DB_PATH",
    "HarnessError",
    "accept_task",
    "add_acceptance",
    "add_failure_mode",
    "add_requirement",
    "add_task",
    "add_test_target",
    "baseline_diff",
    "baseline_validate",
    "block_task",
    "cancel_task",
    "connection",
    "cycle_close",
    "cycle_start",
    "cycle_status",
    "doctor",
    "freeze_baseline",
    "get_store",
    "init_runtime",
    "link_requirement_acceptance",
    "link_task_test_target",
    "list_tasks",
    "list_test_targets",
    "migrate",
    "projection_rebuild",
    "quickstart_minimal",
    "quickstart_status",
    "quickstart_status_lines",
    "record_decision",
    "record_delivery",
    "record_finding",
    "record_gate",
    "record_validation",
    "repair",
    "runtime_initialized",
    "set_store_factory",
    "start_task",
    "status_lines",
    "submit_task",
    "trace_show",
    "trace_validate",
    "transaction",
    "uninitialized_lines",
    "validate_runtime",
    "verify_run",
)


def projection_rebuild(root):
    from core.projections import render_all

    render_all(root)
