"""Explicit public runtime API for Codex Project Harness."""

from __future__ import annotations

from harness_db import (
    DB_PATH,
    HarnessError,
    accept_task,
    apply_delivery_plan,
    add_acceptance,
    add_failure_mode,
    add_requirement,
    add_task,
    add_test_target,
    baseline_diff,
    baseline_validate,
    block_task,
    cancel_task,
    confirm_baseline,
    cycle_audit,
    cycle_close,
    cycle_start,
    cycle_status,
    doctor,
    doctor_operator_report,
    enter_delivery_readiness,
    freeze_baseline,
    init_runtime,
    link_requirement_acceptance,
    link_task_test_target,
    list_tasks,
    list_test_targets,
    migrate,
    outcome_report,
    operator_error_report,
    operator_verbose_lines,
    project_doctor_probe,
    quickstart_minimal,
    quickstart_status,
    quickstart_status_lines,
    quickstart_operator_report,
    qualify_test_target,
    record_outcome_observation,
    record_decision,
    record_delivery,
    record_finding,
    record_gate,
    record_validation,
    render_all as _render_all,
    repair,
    runtime_initialized,
    start_task,
    status_lines,
    status_operator_report,
    submit_task,
    trace_show,
    trace_validate,
    uninitialized_lines,
    uninitialized_operator_report,
    validate_runtime,
    verified_patch,
    verify_run,
)


__all__ = (
    "DB_PATH",
    "HarnessError",
    "accept_task",
    "apply_delivery_plan",
    "add_acceptance",
    "add_failure_mode",
    "add_requirement",
    "add_task",
    "add_test_target",
    "baseline_diff",
    "baseline_validate",
    "block_task",
    "cancel_task",
    "confirm_baseline",
    "cycle_audit",
    "cycle_close",
    "cycle_start",
    "cycle_status",
    "doctor",
    "doctor_operator_report",
    "enter_delivery_readiness",
    "freeze_baseline",
    "init_runtime",
    "link_requirement_acceptance",
    "link_task_test_target",
    "list_tasks",
    "list_test_targets",
    "migrate",
    "outcome_report",
    "operator_error_report",
    "operator_verbose_lines",
    "project_doctor_probe",
    "projection_rebuild",
    "quickstart_minimal",
    "quickstart_status",
    "quickstart_status_lines",
    "quickstart_operator_report",
    "qualify_test_target",
    "record_outcome_observation",
    "record_decision",
    "record_delivery",
    "record_finding",
    "record_gate",
    "record_validation",
    "repair",
    "runtime_initialized",
    "start_task",
    "status_lines",
    "status_operator_report",
    "submit_task",
    "trace_show",
    "trace_validate",
    "uninitialized_lines",
    "uninitialized_operator_report",
    "validate_runtime",
    "verified_patch",
    "verify_run",
)


def projection_rebuild(root):
    _render_all(root)
